FROM openjdk:latest
#FROM jamesdbloom/docker-java8-maven
COPY target/hello-docker-world-1.0.jar /usr/src/hello-docker-world-1.0.jar
CMD java -cp /usr/src/hello-docker-world-1.0.jar techdotbangaru.App
